-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 16:18:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Precio` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_has_categorias` (
  `productos_Id` INT UNSIGNED NOT NULL,
  `categorias_Id` INT NOT NULL,
  PRIMARY KEY (`productos_Id`, `categorias_Id`),
  INDEX `fk_productos_has_categorias_categorias1_idx` (`categorias_Id` ASC) VISIBLE,
  INDEX `fk_productos_has_categorias_productos_idx` (`productos_Id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_categorias_productos`
    FOREIGN KEY (`productos_Id`)
    REFERENCES `mydb`.`productos` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productos_has_categorias_categorias1`
    FOREIGN KEY (`categorias_Id`)
    REFERENCES `mydb`.`categorias` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `perfil_UNIQUE` (`perfil` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sistemas_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sistemas_pago` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `usuarios_Id` INT NOT NULL,
  `sistemas_pago_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `usuarios_Id`),
  INDEX `fk_orden_usuarios1_idx` (`usuarios_Id` ASC) VISIBLE,
  INDEX `fk_orden_sistemas_pago1_idx` (`sistemas_pago_Id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_usuarios1`
    FOREIGN KEY (`usuarios_Id`)
    REFERENCES `mydb`.`usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_sistemas_pago1`
    FOREIGN KEY (`sistemas_pago_Id`)
    REFERENCES `mydb`.`sistemas_pago` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_producto` (
  `id` INT NOT NULL,
  `productos_Id` INT UNSIGNED NOT NULL,
  `orden_Id` INT NOT NULL,
  `orden_usuarios_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_producto_productos1_idx` (`productos_Id` ASC) VISIBLE,
  INDEX `fk_orden_producto_orden1_idx` (`orden_Id` ASC, `orden_usuarios_Id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_producto_productos1`
    FOREIGN KEY (`productos_Id`)
    REFERENCES `mydb`.`productos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_producto_orden1`
    FOREIGN KEY (`orden_Id` , `orden_usuarios_Id`)
    REFERENCES `mydb`.`orden` (`Id` , `usuarios_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id` INT NOT NULL,
  `usuarios_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfil_usuarios1_idx` (`usuarios_Id` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_usuarios1`
    FOREIGN KEY (`usuarios_Id`)
    REFERENCES `mydb`.`usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lugar_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lugar_orden` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `orden_Id` INT NOT NULL,
  `orden_usuarios_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_lugar_orden_orden1_idx` (`orden_Id` ASC, `orden_usuarios_Id` ASC) VISIBLE,
  CONSTRAINT `fk_lugar_orden_orden1`
    FOREIGN KEY (`orden_Id` , `orden_usuarios_Id`)
    REFERENCES `mydb`.`orden` (`Id` , `usuarios_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
